### ISSUE TITLE
 Suggestions for Reducing Reward.

### ISSUE THREAD

**Issue by magnalucus** [ethersocial/proposals#12]
현재 ESN의 채굴 보상량은 1블록에 5 ESN입니다.

현재 블럭타임은 13.5정도이며 엉클블록 비율은 5% 내외입니다.

이 속도로 블록이 생성될 경우 1년동안 생성되는 보상량은 12,264,000 ESN입니다.

만일 1 ESN이 100KRW의 가치를 지니는 경우 1년에 1,226,400,000, 즉 12억 2640만 KRW의 ESN이 채굴 보상으로 주어지게 됩니다.

과도한 보상은 시장에서의 하방압력을 주므로 콘텐츠 보상에 사용하기에 어려움을 줄 수 있다고 판단되는 바 채굴량을 줄이는 것을 제안합니다.

채굴량을 줄이면서 발생할 수 있는 있는 여러가지 문제가 있기 때문에 다양한 논의가 필요합니다.

첫번째로 발생한 수 있는 문제점은 채굴 해시저하입니다.

채굴 해시가 줄어드는 경우 외부 해시에 의한 공격이 발생할 수 있습니다.

1단계로 보상을 줄이는 시점에서 큰 해시저하가 발생할 확률은 적지만, 2단계 이후부터는 해시저하가 발생할 확률이 높습니다.

이 때 해시저하로 인한 해시공격을 받을 수 있으므로 이에대한 대비책이 필요합니다.

이 떄 사용할 수 있는 방법이 Ethereum의 Casper Project의 부분적인 Staking 입니다.

만일 12블록중의 하나를 Staking으로 처리하고 수신처리를 12블록 이상인 경우 인정한다면 

우리는 12컨펌 이상인 블록에 대해서는 안정성을 유지할 수 있게 됩니다.

현재의 블록번호는 # 2,046,818입니다.

최초의 블록보상 저하는 대략적으로 6개월 후인 3,200,000 블록으로 제안합니다.

이후 5,000,000만 블록에서 2차 저하 목표를 제안합니다.

**Comment by ComBba** [comment]
충분히 좋습니다만 좀더 예측모델을 확인 해보는것이 좋겠습니다.

**Comment by magnalucus** [comment]
예. 채굴량 저하로 인한 해시저하와 빈블록공격시 스테이킹의 역할등을 분석해야할 것 같습니다.

**Comment by sharibeads** [comment]
그럼 12블록마다 하나를 스테이킹으로 처리하게되는건가요?
홀더들에게 약간의 보상이 주어진다는게 긍정적으로 보입니다.
그리고 몇개 이상부터 스테이킹이 가능한지도 중요해보입니다. 
또 스테이킹 보상이 거래소에서 지급하게될경우 ESN이 너무 단일 주소로 몰리는 문제가 생길 수 있을듯합니다.(사실 단일 주소로 몰린다고 문제될건없지만. 단 하나. 혹시라도 해킹당할경우 ESN의 큰 타격이 예상되긴합니다.)

**Comment by magnalucus** [comment]
@sharibeads Ethereum Casper를 좀 더 면밀하게 테스트를 해본 후 확정가능합니다.

PoS 노드는 복수개로 지정해서 위험을 분산하고

스테이킹 노드는 폐쇄망에 두어서 외부와의 접속은 피어이외에는 모두 막아야할 것으로 보입니다.

서버를 구축하지 않은 사용자도 컨트랙트로 스테이킹을 추가하는 방안도 마련하겠습니다.

**Comment by hackmod** [comment]
이미 일전에 말씀드린대로, 3,000,000 블록 이후에 자동으로 채굴 보상이 감소합니다. 그 이유는 블록 타임이 3,000,000블록 이후에 서서히 증가합니다. (원래 궤도로 원상복구)

그 이후의 블록보상 감소는 ETC 혹은 Ellaism에서 사용하는 방식을 그대로 따라가면 parity등에서도 손쉽게 지원이 가능해집니다. (500만블록 단위로 감소함)

ETC의 블록보상 감소 제안은 ECIP 1017입니다. https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1017.md

**Comment by magnalucus** [comment]
@hackmod 난이도 폭탄으로 채굴량 감소가 되는 예상량을 알 수 있을까요?

**Comment by hackmod** [comment]
ECIP-1017은 보상 감소와 total supply 제한을 동시에 규정하고 있습니다.
일단 난이도에 의해서 블록타임이 조정이 되므로 etherscan 사이트의 blocktime 및 블록번호를 확인할 수는 있을것입니다. https://etherscan.io/chart/blocktime 및 https://etherscan.io/chart/difficulty 블록번호는 직접 확인해봐야겠네요. 일단 링크만 올립니다.

**Comment by hackmod** [comment]
3,000,000 블록 이후에는 난이도가 천천히 증가합니다.
난이도 폭탄은 이후에 5개월 근처에 발동될 것으로 보이는군요. (대략 80만~90만 블록 이후) 현재 심어진 난이도 폭탄을 제거하기 위해서라도 일단 하드포크는 그 근처 시점에서 필요할 것으로 보입니다.
