### ISSUE TITLE
Suggestion to limit total supply

### ISSUE THREAD

**Issue by magnalucus** [ethersocial/proposals#13]
암호화폐의 일반적인 이슈중의 하나는 총 발행량입니다.

ESN은 이더리움을 기반으로 만들어져서 총 발행량에 대한 제한이 없습니다.

이 때문에 외국에 소개될 때 많은 불이익을 받습니다.

이에 ESN의 총 발행량을 제한할 것을 제안합니다.

급격한 제한은 부작용을 발생시킬 수 있으므로 점진적인 채굴 보상량 감소로 

채굴 보상량이 점차 0으로 가는 무한급수로 전체 채굴량이 수렴하는 방식의 총 발행량 제한을 제안합니다.

**Comment by ComBba** [comment]
총발행량을 3년 이내에 0에 수렴하는 정도보다는점진적으로 10년에 도달할 수 있는 총량을 목표로 감소하는것이 좋을것 같습니다.

**Comment by magnalucus** [comment]
저도 기간이 짧을 필요는 없다고 생각합니다. 총량제한이 있는가? 없는가?가 포인트이지 언제까지 얼마인가?는 큰 이슈가 아니었기 때문입니다.
