### ISSUE TITLE
Youtube Bounty Program

### ISSUE THREAD

**Issue by kimmyeonghun** [ethersocial/proposals#3]
## Proposal

Here is the new ESN bounty program to upload ESN promotional video on Youtube.

## Description

There have been ESN bounty programs related to ESN development so far.

Meanwhile, ESN team and external developers, such as supporters focused on development of ESN and have made various development results of ESN, such as explorers, web wallet, hardware wallet PR, etc.

However, we currently focus on promotion of ESN. It’s pretty important to get interest in ESN from various people all over the world. It should lead to positive effects on trading volume, price growth of ESN in a long term. If you are interested in ESN Youtube bounty program, follow below.

## ESN Youtube Bounty

There are two parts of this bounty

1. Participation bounty - Everyone who uploads ESN promotional video can get 100 ESN

2. View counts bounty – Participants can get additional ESN (view counts times 0.5) depends on view counts of the video in middle of August. It could be August 17. Example: If a participant upload the ESN promotional video and it has 1,000 view counts in August 17, he or she can get 600 ESN (participation bounty 100 ESN + view counts bounty 500 ESN)

## How to join the bounty program

1. Make ESN promotional video

2. Upload the video to Youtube with your ESN wallet address as video information

3. Leave your Youtube link on ESN official twitter as a reply of main twit https://twitter.com/ESNfoundation/status/1024160570906296320

4. Bounty will be distributed during fourth week of August

**Comment by hackmod** [comment]
https://www.youtube.com/channel/UCJbqCUx_Vdi67YvEZRQl3WA
