### ISSUE TITLE
스마트 컨트랙트 ERC20을 쉽게 사용하기에 대한 개발 바운티 프로그램

### ISSUE THREAD

**Issue by magnalucus** [ethersocial/proposals#4]
ESN 프로젝트의 첫번째 목표인 스마트 컨트랙트 ERC20을 쉽게 사용하기에 대한 개발 바운티 프로그램이 오픈됩니다.

ESN은 게임 및 각종 커뮤니티에 블록체인을 쉽게 사용할 수 있게하는 것이 목표입니다.

이를 쉽게 적용하기 위해 다음 내용이 내부 또는 외부에서 개발이 이루어집니다.

1. 커뮤니티 담당자가 ESN 또는 토큰을 사용하기 쉽게 하기 위해 지갑 자체에 ERC토큰을 쉽게 만드는 메뉴 생성.
 * 이름, 수량 등의 정보만 입력하면 토큰 바로 생성
 * 1년간 개발 및 유지보수.
 * 월 바운티 10,000 ESN
 

2. 생성된 토큰의 전송내역을 쉽게 볼 수 있는 익스플로러 개발.
 * 모든 컨트랙트들을 볼 수 있는 환경 제공.
 * 1년간 개발 및 유지보수
 * 월 바운티 10,000ESN

 
3. 위에서 사용하는 토큰에 대한 입출금등에 대한 내역을 받아주는 api 서버
 * ESN을 활용하는 각 커뮤니티에서 각자가 만든 토큰에 대한 입출금 내역을 관리해주는 api
 * etherscan api 와 비슷한 서비스
 * 1년간 개발 및 유지보수
 * 월 바운티 10,000ESN

XE개발자는 흔하지 않으므로 위에서 생성한 토큰을 XE에서 쉽게 사용할 수 있게하는 XE모듈을 별도로 제작해서 무료로 제공하겠습니다.

One of our goals is to make various communities use blockchain readily.
There are three development bounty programs for the goal.

1. Create a menu that easily makes ERC tokens on the wallet itself. It makes community managers use tokens readily.
    1. Directly create tokens with name, amount of tokens
   2. Development and maintenance for 1 year
   3. Bounty: 10,000 ESN per month

2. Develop explorer to check token transactions
   1. Provide tools to check all contracts
   2. Development and maintenance for 1 year
   3. Bounty: 10,000 ESN per month

3. API server that receives token transactions
   1. API that manages token transactions of each individual token in each community which uses ESN
   2. A service similar to ethercan api
   3. Development and maintenance for 1 year
   4. Bounty: 10,000 ESN per month

We will produce XE modules that make the token created above easy to use in XE and provide them for free because XE developers are uncommon.

https://blog.ethersocial.org/open-esn-development-bounty-program-with-erc20-smart-contract/

**Comment by hackmod** [comment]
3개의 제안이 하나에 모두 들어있네요.

spec이 월 바운티 1만개에 걸맞아야 할 것 같습니다 ^^
2번은 바운티는 제가 할당해주시기 바랍니다 :)

**Comment by magnalucus** [comment]
@hackmod Thank you :)
