### ISSUE TITLE
GUI Wallet, ERC 20 hard coding tool. 

### ISSUE THREAD

**Issue by kimmyeonghun** [ethersocial/proposals#5]
스마트 컨트랙트 ERC20 쉽게 사용하기 개발 바운티 프로그램 Ⅰ

- 미스트지갑 또는 에메랄드지갑 등의 GUI지갑에서 지갑 자체에 ERC토큰을 쉽게 만드는 메뉴 생성.
    * 이름, 수량 등의 정보만 입력하면 토큰 바로 생성
    * 1년간 개발 및 유지보수.
    * 월 바운티 10,000 ESN

- Create a menu that easily makes ERC tokens on the wallet itself, Mist or Emerald. 
It makes community managers use tokens readily.
   * Directly create tokens with name, amount of tokens
   * Development and maintenance for 1 year
   * Bounty: 10,000 ESN per month

https://blog.ethersocial.org/open-esn-development-bounty-program-with-erc20-smart-contract/

**Comment by hackmod** [comment]
이 바운티는 바운티 규모를 생각했을때에 다른 바운티와 비교하여 올려놓은 조건이 조금 애매한 측면이 있습니다.

spec을 쉽게 생각하면 너무 쉬워 보이고요. (예를 들어 mist에 토큰 쉽게 만드는 메뉴 넣기는 상대적으로 다른 바운티보다 쉬움)
제대로 개발을 하려면, 최근 mist 개발자들이 매우 열심히 개발하고 있기때문에 잦은 업데이트가 되고 있는데 토큰 기능을 메뉴로 넣은 것을 업스트림 하려는 노력을 한다면 쉬운 것은 아니죠.

그러나, 단순히 토큰 메뉴를 넣은 것으로는 실제로 mist에 업스트림되기가 어려워 보입니다.

차라리 이슈를 여러개 쪼개에서 바운티 규모를 낮추고 쉽게 만드는 것이 어떨까 합니다.

1. 토큰을 쉽게 만들어주는 공개된 오픈소스가 꽤 있습니다. 이를 이용하고, 디자인은 좀더 예쁘고 사용하기 숩게 고쳐, 아주 심플한 토큰 생성할 수 잇는 사이트 제작 - 단회성 바운티 2천 ESN
1. 단순히 이것에만 그치지 않고 ERC20, ERC233 등등을 선택할 수 있게 하고, 메뉴 옵션을 선택하는 것 만으로 손쉬운 토큰 제작 지원 - 추가 1천 ESN
1. 작업물은 완료되는 시점에 오픈소스로 재공개

1. 이와는 별도로, 현재 ESN wallet(미스트기반)이 된 mist는 잦은 업뎃으로 개발자를 골치아프게 하고 있는데, 이것 말고 ETC 에메랄드 지갑이 매우 사용하기 쉽다고 하니, 이 에메랄드 지갑을 ESN용으로 포팅 - 단회성 바운티 2천
2. 이것에 그치지 않고 에메랄드 지갑을 타 코인에 쉽게 적용하기 위해 multi chain 지원 가능하게 업스트림. multi-chain 작업 완료하면 4천, 업스트림이 받아들여지면 3천 추가.
3. 이 이후에 지속적으로 에메랄드 지갑을 관리하고 꾸준히 개선시킨다면 매달 1천 ESN 추가

이정도로 단회성 바운티로 바꾸는 것이 나을 것 같습니다.
